port: 7880

bind_addresses:
  - ""

keys:
  teleop_prod_key: "super_secret_key_for_teleoperation_2026"

redis:
  address: localhost:6379

rtc:
  node_ip: 10.0.39.103
  use_external_ip: false
  udp_port: 50000
  tcp_port: 7881
  congestion_control:
    enabled: true

webhook:
  api_key: teleop_prod_key
  urls:
    - "http://localhost:8080/api/webhook/livekit"

logging:
  level: warn
