appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = mysql
dataSourceName = root:__CASDOOR_DB_ROOT_PASSWORD__@tcp(casdoor-db:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
origin = "https://casdoor.wheelos.cn"
originFrontend = "https://casdoor.wheelos.cn"
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
showGithubCorner = false
forceLanguage = ""
defaultLanguage = "en"
initDataNewOnly = false
initDataFile = "./init_data.json"
frontendBaseDir = "../cc_0"